### ISSUE TITLE
Evalai submissions are not scheduled

### ISSUE THREAD

**Issue by karkuspeter** [facebookresearch/habitat-challenge#61]
Evalai submissions don't seem to be scheduled anymore. I have submissions to pointnav test-std and minival that have remained in "submitted" status for over a week now

**Comment by RishabhJain2018** [comment]
Hi @karkuspeter, Sorry for the delay. The issue is resolved and the submissions are getting processed. There are a bunch of submissions in the queue getting processed and it will take a day or two for your submissions to get processed.
Please feel free to reopen this issue if your submissions don't get processed in a couple of days.

**Comment by karkuspeter** [comment]
Hi @RishabhJain2018, thanks for your help. The issue seemed to be resolved at the time, but now i have another submission (id 94972) stuck in the same state. When i submit new jobs they get scheduled, but the old one is still pending seemingly indefinitely. 
Is there a way for me to detect the issue myself and/or manually cancel jobs?

**Comment by karkuspeter** [comment]
Hi, to follow up on this, my submissions are still not getting scheduled (for over 2 weeks now). 

Its probably unrelated, but when my submissions do get scheduled they often fail on test-std (run for 42 hours and produce empty output). The same container runs successfully locally and on minival. Since i cannot access any output i believe the only option to debug is trial-and-error, but this is extremely slow given that each trial takes multiple weeks to get scheduled.

**Comment by mathfac** [comment]
@karkuspeter, thank you reporting the issue.  Based on https://github.com/facebookresearch/habitat-challenge/issues/62 as I understand scheduling works ok?

**Comment by karkuspeter** [comment]
Yes. I have id=94972 stuck in submitted status since Aug 26, but new submissions after that do get scheduled. I will close the issue now
